import { defaultThemePresetId } from "@/lib/theme-presets";
import { tenant } from "@/lib/tenant";

export const showroomProfileDefaults = {
  themePreset: defaultThemePresetId,
  autoDarkMode: false,
  nameAr: tenant.identity.nameAr,
  nameEn: tenant.identity.nameEn,
  nameHe: tenant.identity.nameHe,
  shortNameAr: tenant.identity.shortNameAr,
  shortNameEn: tenant.identity.shortNameEn,
  shortNameHe: "אבו עיסא",
  taglineAr: tenant.identity.taglineAr,
  taglineEn: tenant.identity.taglineEn,
  taglineHe: "קטלוג רהיטים מסודר לפנייה בוואטסאפ",
  descriptionAr: tenant.identity.descriptionAr,
  descriptionEn: tenant.identity.descriptionEn,
  descriptionHe: "אולם רהיטים בקלקיליה לסלונים, ספות פינתיות, חדרי מגורים ואפשרויות לפי הזמנה.",
  logoPath: "/images/brand/logo.png",
  faviconPath: "/favicon.svg",
  heroImageUrl: "/images/hero-showroom.svg",
  ogImageUrl: "/images/hero-showroom.svg",
  heroTitleAr: tenant.identity.heroTitleAr,
  heroTitleEn: tenant.identity.heroTitleEn,
  heroTitleHe: "רהיטי אבו עיסא",
  heroSubtitleAr: "كتالوج منظم لعرض أطقم الكنب والمفروشات، مع إمكانية حفظ المنتجات التي تعجبك والتواصل مباشرة عبر واتساب للاستفسار عن التفاصيل والتفصيل والتوصيل.",
  heroSubtitleEn: "An organized catalog for sofa sets and furniture, with saved favorites and direct WhatsApp inquiries about details, customization, and delivery.",
  heroSubtitleHe: "קטלוג מסודר לסלונים ורהיטים, עם שמירת פריטים ופנייה ישירה בוואטסאפ לפרטים, התאמה ומשלוח.",
  phone: tenant.contact.phone ?? "00972528682975",
  address: tenant.identity.address.ar,
  city: tenant.identity.city,
  location: tenant.identity.city,
  workingHours: "من السبت إلى الخميس، من الساعة 10 صباحًا حتى 8 مساءً",
  deliveryAreas: tenant.deliveryAreas.map(a => a.nameAr),
  whatsapp: tenant.contact.whatsappNumber,
  email: "",
  social: {
    facebook: tenant.social.facebook ?? "",
    instagram: tenant.social.instagram ?? "",
    tiktok: tenant.social.tiktok ?? ""
  },
  mapLink: "",
  footerTextAr: tenant.texts.footerTextAr,
  footerTextEn: tenant.texts.footerTextEn,
  footerTextHe: "רהיטי אבו עיסא - קלקיליה",
  homepageFeaturedTitleAr: "نماذج مؤقتة للكتالوج",
  homepageFeaturedTitleEn: "Temporary catalog samples",
  homepageFeaturedTitleHe: "דוגמאות זמניות לקטלוג",
  homepageFeaturedSubtitleAr: "سيتم استبدال هذه النماذج بالصور والمنتجات الحقيقية من لوحة الإدارة قبل إطلاق الإعلانات.",
  homepageFeaturedSubtitleEn: "These samples should be replaced from the admin dashboard with real products and photos before ads launch.",
  homepageFeaturedSubtitleHe: "יש להחליף דוגמאות אלה במוצרים ותמונות אמיתיים לפני השקת מודעות.",
  homepageTablesTitleAr: "تفصيل حسب الطلب",
  homepageTablesTitleEn: "Made to order",
  homepageTablesTitleHe: "ייצור לפי הזמנה",
  homepageTablesSubtitleAr: "يمكن تجهيز أقسام المنتجات والصور من لوحة الإدارة عند توفر المحتوى الحقيقي.",
  homepageTablesSubtitleEn: "Product sections and photos can be prepared from the admin dashboard when real content is available.",
  homepageTablesSubtitleHe: "ניתן להכין אזורי מוצרים ותמונות מלוח הניהול כשהתוכן האמיתי יהיה זמין.",
  homepageOffersTitleAr: "العروض والتحديثات",
  homepageOffersTitleEn: "Current offers",
  homepageOffersTitleHe: "מבצעים נוכחיים",
  homepageFabricsTitleAr: "الأقمشة والألوان",
  homepageFabricsTitleEn: "Fabrics and colors",
  homepageFabricsTitleHe: "בדים וצבעים",
  homepageGalleryTitleAr: "معرض الصور",
  homepageGalleryTitleEn: "Image gallery",
  homepageGalleryTitleHe: "גלריית תמונות",
  homepageTrustTitle1Ar: "مقاسات حسب الطلب",
  homepageTrustTitle1En: "Custom measurements",
  homepageTrustTitle1He: "מידות בהתאמה אישית",
  homepageTrustText1Ar: "نساعد الزبون على اختيار التصميم المناسب ومناقشة المقاسات مباشرة عبر واتساب.",
  homepageTrustText1En: "We help visitors choose suitable designs and discuss measurements directly on WhatsApp.",
  homepageTrustText1He: "עוזרים ללקוח לבחור עיצוב מתאים ולדבר על מידות ישירות בוואטסאפ.",
  homepageTrustTitle2Ar: "مساعدة في اختيار القماش",
  homepageTrustTitle2En: "Fabric guidance",
  homepageTrustTitle2He: "עזרה בבחירת בד",
  homepageTrustText2Ar: "يمكن للزبون تصفح الأقمشة والألوان قبل التواصل لتصبح المحادثة أوضح وأسهل.",
  homepageTrustText2En: "Visitors can review fabrics and colors before contacting so the conversation is clearer.",
  homepageTrustText2He: "אפשר לעיין בבדים ובצבעים לפני הפנייה כדי שהשיחה תהיה ברורה יותר.",
  homepageTrustTitle3Ar: "تنسيق التوصيل",
  homepageTrustTitle3En: "Delivery coordination",
  homepageTrustTitle3He: "תיאום משלוח",
  homepageTrustText3Ar: "يتم الاتفاق على تفاصيل التوصيل مباشرة مع المعرض حسب المنطقة والطلب.",
  homepageTrustText3En: "Delivery details are coordinated directly with the showroom by area and order.",
  homepageTrustText3He: "פרטי משלוח מתואמים ישירות עם האולם לפי אזור והזמנה.",
  homepageFaqTitleAr: "أسئلة قبل التواصل",
  homepageFaqTitleEn: "Questions before contacting",
  homepageFaqTitleHe: "שאלות לפני פנייה",
  homepageFaqSubtitleAr: "إجابات قصيرة تساعد الزبون يفهم طريقة التفصيل والطلب عبر واتساب.",
  homepageFaqSubtitleEn: "Short answers that explain customization and WhatsApp inquiry.",
  homepageFaqSubtitleHe: "תשובות קצרות שמסבירות התאמה אישית ופנייה דרך וואטסאפ.",
  homepageFinalTitleAr: "جاهز للاستفسار عن المقاس والقماش والتوصيل؟",
  homepageFinalTitleEn: "Ready to choose size, fabric, and delivery?",
  homepageFinalTitleHe: "מוכנים לבחור מידה, בד ומשלוח?",
  homepageFinalSubtitleAr: tenant.texts.homepageFinalSubtitleAr,
  homepageFinalSubtitleEn: tenant.texts.homepageFinalSubtitleEn,
  homepageFinalSubtitleHe: "שלחו לאולם את העיצובים והבדים שאהבתם בוואטסאפ. אין תשלום באתר ואין מחיר קבוע, רק ייעוץ ישיר.",
  catalogSubtitleAr: "تصفح مجموعة مختارة من أطقم الكنب والمفروشات، واحفظ ما يعجبك ثم تواصل معنا عبر واتساب.",
  catalogSubtitleEn: "Browse selected sofa sets and furniture, save what you like, then contact us on WhatsApp.",
  catalogSubtitleHe: "עיינו בעיצובים הזמינים ושמרו מה שמתאים לפני פנייה בוואטסאפ.",
  fabricsSubtitleAr: "استعرض الأقمشة والألوان لتكون محادثة التفصيل أوضح وأسهل.",
  fabricsSubtitleEn: "Review fabrics and colors so the customization conversation is clearer.",
  fabricsSubtitleHe: "עיינו בבדים ובצבעים כדי ששיחת ההתאמה תהיה ברורה יותר.",
  gallerySubtitleAr: "مساحة جاهزة لصور المعرض الحقيقية عند توفرها.",
  gallerySubtitleEn: "Ready slot for real showroom photos when available.",
  gallerySubtitleHe: "תמונות להמחשה שניתן להחליף בתמונות אמיתיות מהאולם או מעבודות שבוצעו.",
  offersSubtitleAr: "عروض مخصصة للاستشارة عبر واتساب بدون دفع إلكتروني وبدون أسعار ثابتة.",
  offersSubtitleEn: "Offers designed for WhatsApp consultation without checkout or fixed public prices.",
  offersSubtitleHe: "מבצעים לייעוץ בוואטסאפ ללא תשלום באתר וללא מחירים ציבוריים קבועים.",
  contactIntroAr: "تواصل مع المعرض للاستفسار عن المنتجات، التفصيل، الأقمشة، ومناطق التوصيل.",
  contactIntroEn: "Contact the showroom about products, customization, fabrics, and delivery areas.",
  contactIntroHe: "צרו קשר עם האולם בוואטסאפ לשיחה על עיצוב, מידה, בד ומשלוח.",
  defaultWhatsAppTemplateAr: "مرحبًا، أريد الاستفسار عن منتج من الكتالوج.",
  defaultWhatsAppTemplateEn: "Hello, I would like to ask about a catalog product.",
  defaultWhatsAppTemplateHe: "שלום, אשמח לשאול על עיצוב רהיטים.",
  whatsappCtaAr: "استفسار واتساب",
  whatsappCtaEn: "WhatsApp inquiry",
  whatsappCtaHe: "פנייה בוואטסאפ",
  whatsappSheetTitleAr: "إرسال استفسار واتساب",
  whatsappSheetTitleEn: "Send WhatsApp inquiry",
  whatsappSheetTitleHe: "שליחת פנייה בוואטסאפ",
  whatsappSheetSubtitleAr: "اختر المنطقة ونوع الطلب فقط. سنفتح واتساب فورًا.",
  whatsappSheetSubtitleEn: "Choose area and inquiry type only. WhatsApp opens immediately.",
  whatsappSheetSubtitleHe: "בחרו אזור וסוג פנייה בלבד. וואטסאפ ייפתח מיד.",
  whatsappSheetSendLabelAr: "افتح واتساب",
  whatsappSheetSendLabelEn: "Open WhatsApp",
  whatsappSheetSendLabelHe: "פתח וואטסאפ",
  productPriceLabelAr: "تصنيف السعر",
  productPriceLabelEn: "Price label",
  productPriceLabelHe: "רמת מחיר",
  productCustomizationLabelAr: "التفصيل",
  productCustomizationLabelEn: "Customization",
  productCustomizationLabelHe: "התאמה אישית",
  productAvailabilityLabelAr: "التوفر",
  productAvailabilityLabelEn: "Availability",
  productAvailabilityLabelHe: "זמינות",
  productInquiryTitleAr: "ناقش هذا التصميم",
  productInquiryTitleEn: "Discuss this design",
  productInquiryTitleHe: "דברו על העיצוב",
  productInquiryTextAr: "أرسل استفسارك عن هذا المنتج وسنساعدك بالتفاصيل، خيارات الأقمشة، والتوصيل.",
  productInquiryTextEn: "Send your inquiry about this product and we will help with details, fabric options, and delivery.",
  productInquiryTextHe: "שלחו לאולם את קוד העיצוב, המידה הרצויה וכיוון הבד.",
  productFabricsTitleAr: "أقمشة وألوان مرتبطة",
  productFabricsTitleEn: "Linked fabrics and colors",
  productFabricsTitleHe: "בדים וצבעים קשורים",
  productFabricsSubtitleAr: "يفضل تأكيد التوفر عبر واتساب قبل بدء التفصيل.",
  productFabricsSubtitleEn: "Availability should be confirmed through WhatsApp before production.",
  productFabricsSubtitleHe: "מומלץ לאשר זמינות בוואטסאפ לפני ייצור.",
  productRelatedWorkTitleAr: "أعمال مشابهة",
  productRelatedWorkTitleEn: "Related previous work",
  productRelatedWorkTitleHe: "עבודות דומות",
  productRelatedWorkSubtitleAr: "أمثلة تساعد على مقارنة المقاسات والألوان والتشطيب.",
  productRelatedWorkSubtitleEn: "Examples that help compare proportions, colors, and finish.",
  productRelatedWorkSubtitleHe: "דוגמאות להשוואת פרופורציות, צבעים וגימור.",
  productSimilarTitleAr: "تصاميم مشابهة",
  productSimilarTitleEn: "Similar designs",
  productSimilarTitleHe: "עיצובים דומים",
  productSimilarSubtitleAr: "خيارات تفصيل أخرى قريبة في النمط أو التصنيف.",
  productSimilarSubtitleEn: "More custom-made options with related style or category.",
  productSimilarSubtitleHe: "אפשרויות נוספות בהתאמה אישית באותו סגנון או קטגוריה.",
  campaignProductsTitleAr: "تصاميم مختارة",
  campaignProductsTitleEn: "Focused designs",
  campaignProductsTitleHe: "עיצובים נבחרים",
  campaignProductsSubtitleAr: "اختيار مختصر لزائر الإعلان حتى يصل بسرعة إلى استفسار واتساب.",
  campaignProductsSubtitleEn: "A shorter selection for ad visitors who want to move quickly to WhatsApp.",
  campaignProductsSubtitleHe: "בחירה קצרה למבקרי מודעה שרוצים לעבור מהר לוואטסאפ.",
  campaignOffersTitleAr: "عرض مرتبط",
  campaignOffersTitleEn: "Related offer",
  campaignOffersTitleHe: "מבצע קשור",
  campaignOffersSubtitleAr: "بطاقات العروض تبقى مركزة على الاستفسار والتفاوض عبر واتساب.",
  campaignOffersSubtitleEn: "Offer cards stay focused on inquiry and negotiation through WhatsApp.",
  campaignOffersSubtitleHe: "כרטיסי המבצע נשארים ממוקדים בפנייה ומשא ומתן בוואטסאפ.",
  campaignFabricsTitleAr: "أقمشة مناسبة",
  campaignFabricsTitleEn: "Useful fabrics",
  campaignFabricsTitleHe: "בדים מתאימים",
  campaignFabricsSubtitleAr: "نظرة سريعة على اتجاهات الأقمشة التي تناسب هذه الحملة.",
  campaignFabricsSubtitleEn: "A quick look at fabric directions that match this campaign.",
  campaignFabricsSubtitleHe: "מבט קצר על כיווני בדים שמתאימים לקמפיין הזה.",
  campaignEmptyProductsAr: "لم يتم اختيار منتجات لهذه الحملة بعد.",
  campaignEmptyProductsEn: "No products have been selected for this campaign yet.",
  campaignEmptyProductsHe: "עדיין לא נבחרו מוצרים לקמפיין הזה.",
  interestSubtitleAr: "التصاميم والأقمشة والعروض المحفوظة تبقى على هذا الجهاز بدون حساب عميل.",
  interestSubtitleEn: "Saved designs, fabrics, and offers are stored locally on this device without customer login.",
  interestSubtitleHe: "עיצובים, בדים ומבצעים שנשמרו נשארים במכשיר הזה ללא חשבון לקוח.",
  interestEmptyTitleAr: "قائمة الاهتمام فارغة",
  interestEmptyTitleEn: "Your interest list is empty",
  interestEmptyTitleHe: "רשימת העניין ריקה",
  interestEmptyTextAr: "تصفح التصاميم والأقمشة والعروض، ثم احفظ ما تريد مناقشته مع المعرض.",
  interestEmptyTextEn: "Browse designs, fabrics, and offers, then save what you want to discuss with the showroom.",
  interestEmptyTextHe: "עיינו בעיצובים, בדים ומבצעים, ושמרו את מה שתרצו לדון עליו עם האולם.",
  interestBrowseLabelAr: "تصفح التصاميم",
  interestBrowseLabelEn: "Browse designs",
  interestBrowseLabelHe: "עיון בעיצובים",
  interestSendLabelAr: "إرسال عبر واتساب",
  interestSendLabelEn: "Send by WhatsApp",
  interestSendLabelHe: "שליחה בוואטסאפ",
  interestClearLabelAr: "مسح الكل",
  interestClearLabelEn: "Clear all",
  interestClearLabelHe: "נקה הכל",
  interestRemoveLabelAr: "إزالة",
  interestRemoveLabelEn: "Remove",
  interestRemoveLabelHe: "הסר",
  interestDrawerTitleAr: "قائمة الاهتمام",
  interestDrawerTitleEn: "Interest list",
  interestDrawerTitleHe: "רשימת עניין",
  interestDrawerEmptyAr: "احفظ التصاميم والأقمشة والعروض أثناء التصفح. تبقى القائمة على هذا الجهاز بدون تسجيل دخول.",
  interestDrawerEmptyEn: "Save designs, fabrics, and offers while browsing. They stay on this device without login.",
  interestDrawerEmptyHe: "שמרו עיצובים, בדים ומבצעים בזמן הגלישה. הרשימה נשמרת במכשיר הזה ללא התחברות.",
  interestViewPageLabelAr: "عرض الصفحة",
  interestViewPageLabelEn: "View page",
  interestViewPageLabelHe: "הצג עמוד",
  showOffers: true,
  showFabrics: true,
  showGallery: true,
  showPreviousWork: true,
  showFaq: true,
  showFeaturedProducts: true,
  showTablesSection: true,
  showFinalCta: true,
  siteTitleAr: tenant.seo.titleAr,
  siteTitleEn: tenant.seo.titleEn,
  siteTitleHe: "רהיטי אבו עיסא",
  siteDescriptionAr: tenant.seo.descriptionAr,
  siteDescriptionEn: tenant.seo.descriptionEn,
  siteDescriptionHe: "אולם רהיטים בהתאמה אישית לספות, שולחנות, בדים ופנייה בוואטסאפ.",
  faqItems: tenant.defaultFaq,
};

export type FaqItem = {
  questionAr: string;
  questionEn: string;
  questionHe?: string;
  answerAr: string;
  answerEn: string;
  answerHe?: string;
  [key: string]: string | undefined;
};

export type ShowroomProfile = typeof showroomProfileDefaults & {
  social: {
    facebook?: string;
    instagram?: string;
    tiktok?: string;
  };
  faqItems?: FaqItem[];
  [key: string]: unknown;
};

export function normalizeShowroomWhatsApp(value?: string | null) {
  const digits = value?.replace(/\D/g, "") ?? "";
  return digits || tenant.contact.whatsappNumber;
}

const localeSuffixMap: Record<string, "Ar" | "En" | "He"> = {
  ar: "Ar",
  en: "En",
  he: "He"
};

export function localizedProfileValue(profile: ShowroomProfile, field: string, locale: "ar" | "en" | "he") {
  const suffix = localeSuffixMap[locale];
  const key = `${field}${suffix}` as const;
  const value = profile[key as keyof ShowroomProfile];
  return typeof value === "string" && value.trim() ? value : "";
}
